# Generated by Django 5.0.4 on 2024-05-10 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_remove_movie_actors_movie_actors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(blank=True, to='cinema.actor', verbose_name='Актер'),
        ),
    ]
