# Generated by Django 5.0.4 on 2024-05-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_alter_movie_actors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_title', models.CharField(blank=True, choices=[('fantasy', 'Фэнтези'), ('adventures', 'Приключения'), ('action', 'Боевик'), ('drama', 'Драма'), ('thriller', 'Триллер'), ('comedy', 'Комедия')], max_length=20, verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'жанр',
                'verbose_name_plural': 'жанры',
            },
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, to='cinema.genre', verbose_name='Жанр'),
        ),
    ]
